DROP TABLE IF EXISTS cz_products;
DROP TABLE IF EXISTS cz_currency;
DROP TABLE IF EXISTS cz_users_address;
DROP TABLE IF EXISTS cz_users;
DROP TABLE IF EXISTS cz_roles;
DROP TABLE IF EXISTS cz_status;
DROP TABLE IF EXISTS cz_country;