// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID          int64
	UniqueID    string
	RoleID      pgtype.Int4
	FirstName   string
	MiddleName  pgtype.Text
	LastName    string
	Dob         pgtype.Date
	CountryCode string
	Phone       string
	Email       pgtype.Text
	Salt        pgtype.Text
	Password    pgtype.Text
	StatusID    pgtype.Int4
	CreateUser  int32
	ModifyUser  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
}

type CustomersAddress struct {
	ID         int64
	CustomerID pgtype.Int4
	Address1   string
	Address2   pgtype.Text
	Address3   pgtype.Text
	Address4   pgtype.Text
	Location   string
	StatusID   pgtype.Int4
	CreateUser int32
	ModifyUser pgtype.Int4
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
}

type Role struct {
	RoleID     int32
	RoleName   pgtype.Text
	StatusID   pgtype.Int4
	CreateUser int32
	ModifyUser pgtype.Int4
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
	Visible    bool
}

type Status struct {
	ID         int32
	UserStatus string
	CreateUser int32
	ModifyUser pgtype.Int4
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
}
