// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (CzProduct, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CzUser, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (CzVendor, error)
	DeleteProduct(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVendor(ctx context.Context, id int64) error
	GetProduct(ctx context.Context, id int32) (CzProduct, error)
	GetProductForUpdate(ctx context.Context, id int32) (CzProduct, error)
	GetUser(ctx context.Context, id int64) (CzUser, error)
	GetUserForUpdate(ctx context.Context, id int64) (CzUser, error)
	GetVendor(ctx context.Context, id int64) (CzVendor, error)
	GetVendorForUpdate(ctx context.Context, id int64) (CzVendor, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]CzProduct, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]CzVendor, error)
	Listusers(ctx context.Context, arg ListusersParams) ([]CzUser, error)
	UpdateProducts(ctx context.Context, arg UpdateProductsParams) (CzProduct, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (CzUser, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (CzVendor, error)
}

var _ Querier = (*Queries)(nil)
